# Python on Linux Web App
# Build a Python project (using Django/Flask/Bottle frameworks) and deploy it to Azure as a Linux web app.
name: Deploy Python package to Azure Web App as a Linux web app.

on:
  push:
    branches:
      - main

env:
  AZURE_WEBAPP_NAME: hlshop-rcm # set this to your application's name
  WORKING_DIRECTORY: "." # set this to the path to your path of working directory inside github repository, defaults to the repository root
  PYTHON_VERSION: "3.9" # set the version to use
  STARTUP_COMMAND: "python3 main.py" # set this to the startup command required to start the gunicorn server. default it is empty

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    environment: dev
    steps:
      # checkout the repo
      - uses: actions/checkout@v3
      # setup python
      - name: Setup Python
        uses: actions/setup-python@v1
        with:
          python-version: ${{ env.PYTHON_VERSION }}
      # install dependencies
      - name: python install
        working-directory: ${{ env.WORKING_DIRECTORY }}
        run: |
          python${{ env.PYTHON_VERSION }} -m venv antenv
          source antenv/bin/activate
          pip install setuptools
          pip install -r requirements.txt

      # deploy web app
      - uses: azure/webapps-deploy@v2
        with:
          app-name: ${{ env.AZURE_WEBAPP_NAME }}
          package: ${{ env.WORKING_DIRECTORY }}
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
