# Python on Linux Web App
# Build a Python project (using Django/Flask/Bottle frameworks) and deploy it to Azure as a Linux web app.
name: Deploy Python package to Azure Web App as a Linux web app.

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    environment: dev
    steps:
      # checkout the repo
      - uses: actions/checkout@v3
      # setup python
      - name: Setup Python
        uses: actions/setup-python@v1
        with:
          python-version: "3.9"
      # install dependencies
      - name: python install
        working-directory: .
        run: |
          python3.9 -m venv antenv
          source antenv/bin/activate
          pip install setuptools
          pip install -r requirements.txt

      - name: Deploy to Azure App Service
        uses: azure/webapps-deploy@v2
        with:
          app-name: hlshop-rcm
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
          package: .
